/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DanhBaDAO;
import DAO.TaiKhoanDAO;
import POJO.DanhBa;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.util.List;


/**
 *
 * @author levan
 */
public class FormDanhBa extends javax.swing.JFrame {

    /**
     * Creates new form FormDanhBa
     */
    
     private int maTaiKhoan; 
     private String username;
   
    
    DefaultTableModel dtm=new DefaultTableModel();
    public FormDanhBa(int maTaiKhoan, String username) { 
        initComponents();
        this.username = username;
        lblTen.setText("Xin chào, " + username); 
        this.maTaiKhoan = maTaiKhoan; 
        LoadTable();
        selectionModel();
        txtMaLienHe.setEnabled(false);
        LienKet.setSelectedIndex(2);
        txt_mlh.setEnabled(false);
        txt_mlh.setVisible(false);
        txtMaLienHe.setText(String.valueOf(DanhBaDAO.getMaxMaLienHeFromDatabase() + 1));
        txt_mlh.setText(String.valueOf(DanhBaDAO.getMaxMaLienHeFromDatabase() + 1));
        txtMaLienHe.setVisible(false);
        LoadComboBox();
    }
    private void LoadComboBox(){
      
        ArrayList<String> columnHeaders = new ArrayList<>();
        
        columnHeaders.add("Tên");
        columnHeaders.add("Số điện thoại");
        columnHeaders.add("Email");
        columnHeaders.add("Địa chỉ");
        columnHeaders.add("Ngày sinh");

     
        for (String header : columnHeaders) {
            cbb_TimKiem.addItem(header);
        } 
        cbb_TimKiem.addActionListener(e -> {
      
        });
    }
    private void LoadTable() {
        this.setLocationRelativeTo(null);
        String[] tieuDe = {"Mã Liên Hệ", "Họ Tên", "Số Điện Thoại", "Email", "Địa chỉ", "Ngày Sinh"};
        dtm.setColumnIdentifiers(tieuDe);
        ArrayList<DanhBa> dsDB = DanhBaDAO.showdsDB(maTaiKhoan); // Sử dụng mã tài khoản
        dtm.setRowCount(0);
        for (DanhBa db : dsDB) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(db.getMaLienHe());
            vec.add(db.getTen());
            vec.add(db.getSoDienThoai());
            vec.add(db.getEmail());
            vec.add(db.getDiaChi());
            vec.add(db.getNgaySinh());
            dtm.addRow(vec);
        }
        dsDanhBa.setModel(dtm);
        
        dsDanhBa.getColumnModel().getColumn(0).setMinWidth(0);
        dsDanhBa.getColumnModel().getColumn(0).setMaxWidth(0);
        dsDanhBa.getColumnModel().getColumn(0).setWidth(0);
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LienKet = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        txtMaLienHe = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsDanhBa = new javax.swing.JTable();
        txt_mlh = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtht = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txte = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtns = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        btn_Xuat = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_Nhap = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbb_TimKiem = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_DanhBa = new javax.swing.JButton();
        btn_TrangChu = new javax.swing.JButton();
        btn_TaoLienHe = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_DangXuat = new javax.swing.JButton();
        lblTen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaLienHe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMaLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLienHeActionPerformed(evt);
            }
        });

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên:");

        txtSoDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Số điện thoại:");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNgaySinh.setForeground(new java.awt.Color(153, 153, 153));
        txtNgaySinh.setText("ex: 03-03-2003");
        txtNgaySinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNgaySinhFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNgaySinhFocusLost(evt);
            }
        });
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Ngày sinh:");

        btn_Add.setBackground(new java.awt.Color(102, 102, 102));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Thêm liên hệ");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtMaLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_Add)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        LienKet.addTab("Tạo liên hệ", jPanel5);

        dsDanhBa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dsDanhBa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsDanhBa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsDanhBaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsDanhBa);

        txt_mlh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_mlh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mlhActionPerformed(evt);
            }
        });

        txtsdt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Số Điện Thoại:");

        txtdc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Địa chỉ");

        txtht.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Họ Tên:");

        txte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Email:");

        txtns.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtns.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnsFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Ngày Sinh:");

        txt_TimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btn_TimKiem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 0));
        btn_Xoa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa Liên Hệ");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(0, 255, 0));
        btn_CapNhat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setText("Cập Nhật Liên Hệ");
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        btn_Xuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/export (2).png"))); // NOI18N
        btn_Xuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restart.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_Nhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/downloads.png"))); // NOI18N
        btn_Nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhapActionPerformed(evt);
            }
        });

        jLabel15.setText("Tìm kiếm");

        jButton1.setText("Xóa tất cả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtht, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mlh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btn_Xoa)
                                .addGap(28, 28, 28)
                                .addComponent(btn_CapNhat)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_mlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Xuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Nhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Xoa)
                            .addComponent(btn_CapNhat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        LienKet.addTab("Danh bạ", jPanel2);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Wellcome!!!!!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16))
        );

        LienKet.addTab("Trang chủ", jPanel1);

        getContentPane().add(LienKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, -40, 680, 630));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phone-book (1).png"))); // NOI18N
        jLabel9.setText("DANH BẠ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_DanhBa.setBackground(new java.awt.Color(102, 102, 102));
        btn_DanhBa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DanhBa.setForeground(new java.awt.Color(255, 255, 255));
        btn_DanhBa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact.png"))); // NOI18N
        btn_DanhBa.setText(" Danh bạ");
        btn_DanhBa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DanhBaActionPerformed(evt);
            }
        });

        btn_TrangChu.setBackground(new java.awt.Color(102, 102, 102));
        btn_TrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btn_TrangChu.setText("Trang chủ");
        btn_TrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrangChuActionPerformed(evt);
            }
        });

        btn_TaoLienHe.setBackground(new java.awt.Color(102, 102, 102));
        btn_TaoLienHe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TaoLienHe.setForeground(new java.awt.Color(255, 255, 255));
        btn_TaoLienHe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_2997933 (1).png"))); // NOI18N
        btn_TaoLienHe.setText(" Tạo liên hệ");
        btn_TaoLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoLienHeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        btn_DangXuat.setText("Đăng xuất");
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });

        lblTen.setForeground(new java.awt.Color(255, 255, 255));
        lblTen.setText("jLabel17");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_DangXuat)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DangXuat)
                    .addComponent(lblTen))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_TaoLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_DanhBa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(btn_TrangChu)
                .addGap(37, 37, 37)
                .addComponent(btn_DanhBa)
                .addGap(42, 42, 42)
                .addComponent(btn_TaoLienHe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(505, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DanhBaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DanhBaActionPerformed
        // TODO add your handling code here:
        LienKet.setSelectedIndex(1);
    }//GEN-LAST:event_btn_DanhBaActionPerformed

    private void btn_TrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrangChuActionPerformed
        // TODO add your handling code here:
        LienKet.setSelectedIndex(2);
    }//GEN-LAST:event_btn_TrangChuActionPerformed

    private void btn_TaoLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoLienHeActionPerformed
        // TODO add your handling code here:
        LienKet.setSelectedIndex(0);
    }//GEN-LAST:event_btn_TaoLienHeActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.dispose(); // Đóng form hiện tại
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
          // TODO add your handling code here:
        int malienhe = Integer.parseInt(txtMaLienHe.getText());
        String ten = txtHoTen.getText(); // Lấy dữ liệu từ trường tên
        int soDienThoai = 0;
        String email = txtEmail.getText(); // Lấy dữ liệu từ trường email
        String diaChi = txtDiaChi.getText(); // Lấy dữ liệu từ trường địa chỉ
        String ngaySinhStr = txtNgaySinh.getText();

        // Kiểm tra xem trường Tên có được nhập hay không
        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập Tên!");
            return; // Dừng xử lý tiếp theo nếu không có Tên
        }
         if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập Địa chỉ!");
            return; // Dừng xử lý tiếp theo nếu không có Tên
        }

        // Kiểm tra xem trường số điện thoại có chứa dữ liệu hợp lệ hay không
        if (!txtSoDienThoai.getText().isEmpty()) {
            try {
                soDienThoai = Integer.parseInt(txtSoDienThoai.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ!");
                return; // Dừng xử lý tiếp theo nếu số điện thoại không hợp lệ
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại!");
            return; // Dừng xử lý tiếp theo nếu không có số điện thoại
        }

        // Kiểm tra xem email có chứa ký tự "@" hay không
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ!");
            return; // Dừng xử lý tiếp theo nếu email không hợp lệ
        }

        // Kiểm tra xem ngày sinh có được nhập đúng định dạng hay không
        Date ngaySinh = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); // Định dạng ngày
            ngaySinh = sdf.parse(ngaySinhStr); // Chuyển chuỗi thành đối tượng Date
        } catch (ParseException ex) {
            // Xử lý nếu không thể chuyển đổi chuỗi thành ngày
            JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
            return; // Dừng xử lý tiếp theo nếu ngày sinh không hợp lệ
        }

        // Kiểm tra ngày sinh đã được chuyển đổi thành công hay không
        if (ngaySinh != null) {
            // Tạo đối tượng DanhBa từ dữ liệu lấy được
            DanhBa newContact = new DanhBa(malienhe, ten, soDienThoai, email, diaChi, ngaySinh);
            // Gọi phương thức thêmDanhBa từ lớp DAO và kiểm tra kết quả
            if (DanhBaDAO.themDanhBa(newContact, maTaiKhoan)) {
                // Thông báo thành công nếu thêm thành công
                JOptionPane.showMessageDialog(null, "Thêm dữ liệu thành công!");
                // Xóa nội dung của các trường văn bản
                txtMaLienHe.setText(String.valueOf(DanhBaDAO.getMaxMaLienHeFromDatabase() + 1));
                txtHoTen.setText("");
                txtSoDienThoai.setText("");
                txtEmail.setText("");
                txtDiaChi.setText("");
                txtNgaySinh.setText("ex: 03-03-2003");
                txtNgaySinh.setForeground(new Color(153, 153, 153));
            } else {
                // Thông báo lỗi nếu thêm không thành công
                JOptionPane.showMessageDialog(null, "Thêm dữ liệu thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lỗi ngày sinh không hợp lệ");
        }

        LoadTable();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void txtNgaySinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgaySinhFocusLost
        // TODO add your handling code here:

        if(txtNgaySinh.getText().equals(""))
        {
            txtNgaySinh.setText("ex: 03-03-2003");
            txtNgaySinh.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNgaySinhFocusLost

    private void txtNgaySinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgaySinhFocusGained
        // TODO add your handling code here:
        if(txtNgaySinh.getText().equals("ex: 03-03-2003"))
        {
            txtNgaySinh.setText("");
            txtNgaySinh.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNgaySinhFocusGained

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtMaLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLienHeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLienHeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Lấy mã tài khoản của người dùng đang đăng nhập
        int maTaiKhoanDangNhap = TaiKhoanDAO.getMaTaiKhoan(username); // Đây là phương thức bạn cần có để lấy mã tài khoản đang đăng nhập

        // Hiển thị hộp thoại xác nhận trước khi xóa tất cả các liên hệ
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa tất cả các liên hệ cho tài khoản này?", "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Gọi phương thức xoaTatCaDanhBaTheoMaTaiKhoan từ lớp DAO và kiểm tra kết quả
            if (DanhBaDAO.xoaTatCaDanhBaTheoMaTaiKhoan(maTaiKhoanDangNhap)) {

                JOptionPane.showMessageDialog(null, "Lỗi! Không thể xóa tất cả dữ liệu.");
            } else {

                JOptionPane.showMessageDialog(null, "Xóa tất cả dữ liệu thành công!");
            }
            LoadTable(); // Đây là phương thức bạn sử dụng để làm mới bảng sau khi xóa dữ liệu
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_NhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhapActionPerformed
        // TODO add your handling code here:
        // Mở hộp thoại chọn file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Open");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xlsx"));
        int userSelection = fileChooser.showOpenDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();

            // Nhập dữ liệu từ file Excel
            List<DanhBa> danhBaList = DanhBaDAO.importFromExcel(filePath);

            // Cập nhật cơ sở dữ liệu hoặc giao diện với dữ liệu đã nhập
            for (DanhBa danhBa : danhBaList) {
                // Gọi phương thức thêmDanhBa từ lớp DAO và kiểm tra kết quả
                if (DanhBaDAO.themDanhBa(danhBa,maTaiKhoan)) {
                    // Cập nhật giao diện hoặc cơ sở dữ liệu
                    System.out.println("Thêm dữ liệu thành công: " + danhBa.getTen());

                } else {
                    System.out.println("Thêm dữ liệu thất bại: " + danhBa.getTen());
                }
            }

            // Load lại bảng dữ liệu trên giao diện
            LoadTable();
            txtMaLienHe.setText(String.valueOf(DanhBaDAO.getMaxMaLienHeFromDatabase() + 1));
            // Hiển thị thông báo kết quả
            JOptionPane.showMessageDialog(null, "Nhập dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Hủy chọn file.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_NhapActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LoadTable();
        txtMaLienHe.setText(String.valueOf(DanhBaDAO.getMaxMaLienHeFromDatabase() + 1));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_XuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatActionPerformed
        // TODO add your handling code here:
        // Lấy danh sách liên hệ từ bảng hoặc từ cơ sở dữ liệu
        List<DanhBa> danhBaList = DanhBaDAO.showdsDB(maTaiKhoan);

        // Chọn đường dẫn lưu file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save as");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xlsx"));
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            // Xuất dữ liệu ra file Excel
            DanhBaDAO.exportToExcel(danhBaList, filePath);
            JOptionPane.showMessageDialog(null, "Xuất dữ liệu thành công!");
        }
    }//GEN-LAST:event_btn_XuatActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin mới từ các trường văn bản
        int maLienHe = Integer.parseInt(txt_mlh.getText());
        String ten = txtht.getText();
        int soDienThoai = Integer.parseInt(txtsdt.getText());
        String email = txte.getText();
        String diaChi = txtdc.getText();
        String ngaySinhStr = txtns.getText();

        // Chuyển đổi ngày sinh từ chuỗi sang đối tượng Date
        Date ngaySinh = null;
        try {
            ngaySinh = new SimpleDateFormat("dd-MM-yyyy").parse(ngaySinhStr);
        } catch (ParseException ex) {
            ex.printStackTrace();
            // Hiển thị thông báo lỗi nếu ngày sinh không hợp lệ
            JOptionPane.showMessageDialog(null, "Lỗi! Ngày sinh không hợp lệ.");
            return; // Dừng việc cập nhật nếu có lỗi xảy ra
        }

        // Tạo đối tượng DanhBa mới với thông tin đã cập nhật
        DanhBa updatedContact = new DanhBa(maLienHe, ten, soDienThoai, email, diaChi, ngaySinh);

        // Gọi phương thức cập nhật từ lớp DAO và kiểm tra kết quả
        if (DanhBaDAO.capNhatDanhBa(updatedContact)) {
            // Hiển thị thông báo cập nhật thành công
            JOptionPane.showMessageDialog(null, "Cập nhật thông tin thành công!");
        } else {
            // Hiển thị thông báo lỗi nếu cập nhật không thành công
            JOptionPane.showMessageDialog(null, "Lỗi! Không thể cập nhật thông tin.");
        }

        // Cập nhật lại bảng
        LoadTable();
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // Lấy mã liên hệ từ trường văn bản
        int maLienHe = Integer.parseInt(txt_mlh.getText());

        // Gọi phương thức xóaDanhBa từ lớp DAO và kiểm tra kết quả
        if (DanhBaDAO.xoaDanhBa(maLienHe)) {
            // Hiển thị thông báo xóa thành công
            JOptionPane.showMessageDialog(null, "Xóa dữ liệu thành công!");
        } else {
            // Hiển thị thông báo lỗi nếu xóa không thành công
            JOptionPane.showMessageDialog(null, "Lỗi! Không thể xóa dữ liệu.");
        }
        LoadTable();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed

          // Lấy từ khóa tìm kiếm từ trường văn bản
    String keyword = txt_TimKiem.getText();

    // Lấy chỉ mục của mục được chọn trong combobox
    int selectedIndex = cbb_TimKiem.getSelectedIndex();

        // Tạo một biến để lưu trữ tên cột cần tìm kiếm
        String columnName = "";

        // Xác định tên cột cần tìm kiếm dựa trên chỉ mục của mục được chọn trong combobox
        switch (selectedIndex) {
                     
            case 0:
                columnName = "Ten";
                break;
            case 1:
                columnName = "SoDienThoai";
                break;
            case 2:
                columnName = "Email";
                break;
            case 3:
                columnName = "DiaChi";
                break;
            case 4:
                columnName = "NgaySinh";
                break;       
            default:
                break;
        }

        // Gọi phương thức tìm kiếm từ lớp DAO dựa trên tên cột và từ khóa tìm kiếm
        ArrayList<DanhBa> dsDB = DanhBaDAO.timKiemDanhBa(columnName, keyword, maTaiKhoan);

        // Cập nhật bảng hiển thị danh bạ với kết quả tìm kiếm
        updateTable(dsDB);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void txtnsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnsFocusLost
       
    }//GEN-LAST:event_txtnsFocusLost

    private void txtnsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnsFocusGained
      
    }//GEN-LAST:event_txtnsFocusGained

    private void txt_mlhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mlhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mlhActionPerformed

    private void dsDanhBaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsDanhBaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dsDanhBaMouseClicked
        
       
    private void updateTable(ArrayList<DanhBa> dsDB) {
        // Lấy mô hình bảng hiện tại
        DefaultTableModel model = (DefaultTableModel) dsDanhBa.getModel();

        // Xóa tất cả các hàng hiện tại trong bảng
        model.setRowCount(0);

        // Thêm các hàng mới vào bảng
        for (DanhBa db : dsDB) {
            model.addRow(new Object[]{db.getMaLienHe(), db.getTen(), db.getSoDienThoai(), db.getEmail(), db.getDiaChi(), db.getNgaySinh()});
        }
    }
    private void selectionModel()
    {
            //Thêm sự kiện lắng nghe cho bảng
        dsDanhBa.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                //Lấy hàng được chọn
                int selectedRow = dsDanhBa.getSelectedRow();
                //Kiểm tra nếu có hàng được chọn
                if (selectedRow != -1) {
                    //Lấy dữ liệu từ hàng được chọn và hiển thị lên các trường văn bản tương ứng
                    txt_mlh.setText(dsDanhBa.getValueAt(selectedRow, 0).toString()); 
                    txtht.setText(dsDanhBa.getValueAt(selectedRow, 1).toString()); 
                    txtsdt.setText(dsDanhBa.getValueAt(selectedRow, 2).toString()); 
                    txte.setText(dsDanhBa.getValueAt(selectedRow, 3).toString()); 
                    txtdc.setText(dsDanhBa.getValueAt(selectedRow, 4).toString()); 
                    txtns.setText(dsDanhBa.getValueAt(selectedRow, 5).toString()); 
                    //Có thể tiếp tục với các trường khác tương tự
                }
            }
        }
    });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDanhBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDanhBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDanhBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDanhBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane LienKet;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_DanhBa;
    private javax.swing.JButton btn_Nhap;
    private javax.swing.JButton btn_TaoLienHe;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TrangChu;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_Xuat;
    private javax.swing.JComboBox<String> cbb_TimKiem;
    private javax.swing.JTable dsDanhBa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaLienHe;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_mlh;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txte;
    private javax.swing.JTextField txtht;
    private javax.swing.JTextField txtns;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
